In [2]:
import numpy as np
print(np.__version__)
import matplotlib.pyplot as plt

1.19.5


# Numpy Basics:


**Exercise #1:** Creating a numpy array with particular value

**Your Task** Create a numpy array with size 2*3 with all elements as 5.

In [ ]:
# YOUR CODE STARTS HERE
arr = np.full((2,3), 5)
# YOUR CODE ENDS HERE
print(arr)

[[5 5 5]
 [5 5 5]]


**Exercise #2:** Creating a numpy array with *random* value

**Your Task** Create a numpy array with size 2*3 with all random values

In [ ]:
# YOUR CODE STARTS HERE
rand_arr = np.random.random((2,3))
# YOUR CODE ENDS HERE
print(rand_arr)

[[0.38953313 0.95490812 0.14454383]
 [0.49232136 0.69345571 0.94685292]]


**Exercise #3:** Basic NumPy operatrions

**Your Task** For the random array `arr`defined above, find the `sum` of all the elements, `mean`, `maximum` and `minimum` value 

In [ ]:
#YOUR CODE STARTS HERE
arr_sum = np.sum(arr)
arr_mean = np.mean(arr)
arr_max = np.max(arr)
arr_min = np.min(arr)
#YOUR CODE ENDS HERE

print(f'sum: {arr_sum}\nmean: {arr_mean}\nmax: {arr_max}\nmin: {arr_min}')

sum: 30
mean: 5.0
max: 5
min: 5


**Exercise #4:** `argmin` and `argmax`

**Your Task** For the random array `arr`defined below:

*   Find the position of maximum and minimum value of above array
*   Find the indices of maximum and minimum value along each of its columns.
*   Find the indices of maximum and minimum value along each of the its rows.



In [4]:
# Define an array
arr = np.array([[5,12,51,25] ,[25,29,2,27]])
print(f'Array:\n{arr}\n')
# YOUR CODE STARTS HERE
#Find the position of maximum and minimum value of above array
max_idx = np.unravel_index(np.argmax(arr), arr.shape)
min_idx = np.unravel_index(np.argmin(arr), arr.shape)
print(max_idx,min_idx)

#Find the indices of maximum and minimum value along each of its columns.
max_col = np.argmax(arr, axis=0)
min_col = np.argmin(arr, axis=0)
print(max_col,min_col)

#Find the indices of maximum and minimum value along each of the its rows.
max_row = np.argmax(arr, axis=1)
min_row = np.argmin(arr, axis=1)
print(max_row,min_row)
#YOUR CODE ENDS HERE

Array:
[[ 5 12 51 25]
 [25 29  2 27]]

(0, 2) (1, 2)
[1 1 0 1] [0 0 1 0]
[2 1] [0 2]
